# Generated by Django 6.1 on 2026-09-16 11:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssn', models.CharField(help_text='Finnish personal identity code (Henkilotunnus).', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Not in the expected Finnish henkilotunnus format (e.g. 010101-1234).', regex='^\\d{6}[-+A]\\d{3}[0-9A-Y]$')], verbose_name='henkilötunnus')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='sukunimi')),
                ('first_names', models.CharField(blank=True, max_length=100, verbose_name='etunimet')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='syntymäaika')),
                ('street_address', models.CharField(blank=True, max_length=200, verbose_name='lähiosoite')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postinumero')),
                ('postal_district', models.CharField(blank=True, max_length=100, verbose_name='postitoimipaikka')),
                ('address_protected', models.BooleanField(default=False, help_text="True if this person's VTJ record has an active address-protection flag (Turvakielto).", verbose_name='turvakielto')),
            ],
            options={
                'verbose_name': 'guardian',
                'verbose_name_plural': 'guardians',
                'ordering': ['last_name', 'first_names'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssn', models.CharField(help_text='Finnish personal identity code (Henkilotunnus).', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Not in the expected Finnish henkilotunnus format (e.g. 010101-1234).', regex='^\\d{6}[-+A]\\d{3}[0-9A-Y]$')], verbose_name='henkilötunnus')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='sukunimi')),
                ('first_names', models.CharField(blank=True, max_length=100, verbose_name='etunimet')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='syntymäaika')),
                ('street_address', models.CharField(blank=True, max_length=200, verbose_name='lähiosoite')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postinumero')),
                ('postal_district', models.CharField(blank=True, max_length=100, verbose_name='postitoimipaikka')),
                ('address_protected', models.BooleanField(default=False, help_text="True if this person's VTJ record has an active address-protection flag (Turvakielto).", verbose_name='turvakielto')),
                ('guardians', models.ManyToManyField(blank=True, related_name='dependants', to='vtj.guardian')),
            ],
            options={
                'verbose_name': 'dependant',
                'verbose_name_plural': 'dependants',
                'ordering': ['last_name', 'first_names'],
                'abstract': False,
            },
        ),
    ]
