# Generated by Django 6.1 on 2026-09-10 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreschoolApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hakenut_ensisijaisesti_yksityiseen', models.BooleanField(default=False, verbose_name='Onko hakenut ensisijaisesti yksityiseen päiväkotiin')),
                ('kieli', models.CharField(blank=True, choices=[('fi', 'Suomi'), ('sv', 'Ruotsi')], max_length=2, verbose_name='Esiopetuksen kieli')),
                ('taydentava_varhaiskasvatus', models.BooleanField(default=False, verbose_name='Tarvitseeko täydentävää varhaiskasvatusta')),
                ('taydentava_varhaiskasvatus_aloitus', models.DateField(blank=True, null=True, verbose_name='Täydentävän varhaiskasvatuksen aloituspäivä')),
                ('hoidon_tarve', models.CharField(blank=True, choices=[('paivaaikainen_varhaiskasvatus', 'Esiopetus 4 tuntia jonka lisäksi päiväaikainen varhaiskasvatus'), ('paiva_ja_ilta_aikainen_varhaiskasvatus_arkisin', 'Esiopetus 4 tuntia jonka lisäksi päivä- ja ilta-aikainen varhaiskasvatus arkisin'), ('ymparivuorokautinen_varhaiskasvatus', 'Esiopetus 4 tuntia jonka lisäksi ympärivuorokautinen varhaiskasvatus')], max_length=64, verbose_name='Vuorohoidon tarve')),
                ('palvelun_tarve', models.CharField(blank=True, choices=[('esiopetus_4h_1h_vaka', 'Esiopetus 4h + 1h vaka'), ('esiopetus_4h_1_3h_vaka', 'Esiopetus 4h + 1-3h vaka'), ('esiopetus_4h_3_4h_vaka', 'Esiopetus 4h + 3-4h vaka'), ('esiopetus_4h_4_6h_vaka', 'Esiopetus 4h + 4-6h vaka')], max_length=32, verbose_name='Laajuus yhteensä')),
                ('arkipoissaolot_lkm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Arkipoissaolojen lukumäärä')),
                ('erityisen_tuen_tarve', models.BooleanField(default=False, verbose_name='Erityisen tuen tarve')),
                ('laakehoidon_tarve', models.BooleanField(default=False, verbose_name='Lääkehoidon tarve')),
                ('nimi', models.CharField(blank=True, max_length=255, verbose_name='Lapsen nimi')),
                ('henkilotunnus', models.CharField(blank=True, max_length=11, verbose_name='Henkilötunnus')),
                ('karttaosoite', models.CharField(blank=True, max_length=255, verbose_name='Karttaosoite')),
                ('syntymavuosi', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Syntymävuosi')),
                ('h1_nimi', models.CharField(blank=True, max_length=255, verbose_name='Huoltaja 1 nimi')),
                ('h1_osoite', models.CharField(blank=True, max_length=255, verbose_name='Huoltaja 1 osoite')),
                ('h1_sahkoposti', models.EmailField(blank=True, max_length=254, verbose_name='Huoltaja 1 sähköposti')),
                ('h1_puhelinnumero', models.CharField(blank=True, max_length=20, verbose_name='Huoltaja 1 puhelinnumero')),
                ('h2_nimi', models.CharField(blank=True, max_length=255, verbose_name='Huoltaja 2 nimi')),
                ('h2_osoite', models.CharField(blank=True, max_length=255, verbose_name='Huoltaja 2 osoite')),
                ('h2_sahkoposti', models.EmailField(blank=True, max_length=254, verbose_name='Huoltaja 2 sähköposti')),
                ('h2_puhelinnumero', models.CharField(blank=True, max_length=20, verbose_name='Huoltaja 2 puhelinnumero')),
            ],
            options={
                'verbose_name': 'Esiopetushakemus',
                'verbose_name_plural': 'Esiopetushakemukset',
            },
        ),
    ]
