# Generated by Django 6.1 on 2026-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preschoolapplication',
            name='taydentava_varhaiskasvatus_aloitus',
            field=models.DateField(blank=True, help_text='Date in ISO 8601 format (YYYY-MM-DD).', null=True, verbose_name='Täydentävän varhaiskasvatuksen aloituspäivä'),
        ),
    ]
