# Generated by Django 6.1 on 2026-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_alter_preschoolapplication_taydentava_varhaiskasvatus_aloitus'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschoolapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16, verbose_name='Tila'),
        ),
        migrations.AddField(
            model_name='preschoolapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lähetetty'),
        ),
        migrations.AlterField(
            model_name='preschoolapplication',
            name='erityisen_tuen_tarve',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Erityisen tuen tarve'),
        ),
        migrations.AlterField(
            model_name='preschoolapplication',
            name='hakenut_ensisijaisesti_yksityiseen',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Onko hakenut ensisijaisesti yksityiseen päiväkotiin'),
        ),
        migrations.AlterField(
            model_name='preschoolapplication',
            name='laakehoidon_tarve',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Lääkehoidon tarve'),
        ),
        migrations.AlterField(
            model_name='preschoolapplication',
            name='taydentava_varhaiskasvatus',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Tarvitseeko täydentävää varhaiskasvatusta'),
        ),
    ]
