# Generated by Django 6.1 on 2026-09-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0003_preschoolapplication_status'),
        ('vtj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschoolapplication',
            name='dependant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vtj.dependant', verbose_name='Lapsi'),
        ),
    ]
