# Generated by Django 6.1 on 2026-10-08 12:32

from django.db import migrations, models

OLD_HOIDON_TARVE_VALUES = ["paiva_ja_ilta_aikainen_varhaiskasvatus_arkisin", "ymparivuorokautinen_varhaiskasvatus"]


def migrate_hoidon_tarve(apps, schema_editor):
    PreschoolApplication = apps.get_model("guardian", "PreschoolApplication")
    PreschoolApplication.objects.filter(hoidon_tarve__in=OLD_HOIDON_TARVE_VALUES).update(hoidon_tarve="vuorohoito_varhaiskasvatus")


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0004_preschoolapplication_dependant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preschoolapplication',
            name='hoidon_tarve',
            field=models.CharField(blank=True, choices=[('paivaaikainen_varhaiskasvatus', 'Esiopetus 4 tuntia jonka lisäksi päiväaikainen varhaiskasvatus'), ('vuorohoito_varhaiskasvatus', 'Esiopetus 4 tuntia arkisin, jonka lisäksi vuorohoidon tarve varhaiskasvatuksessa')], max_length=64, verbose_name='Vuorohoidon tarve'),
        ),
        migrations.AlterField(
            model_name='preschoolapplication',
            name='palvelun_tarve',
            field=models.CharField(blank=True, choices=[('esiopetus_4h_1h_vaka', 'Esiop +päiväh, yht 5t/pv'), ('esiopetus_4h_1_3h_vaka', 'Esiop+ päiväh, yht 5-7/pv'), ('esiopetus_4h_3_4h_vaka', 'Esiop +päiväh, yht 7-8/pv'), ('esiopetus_4h_4_6h_vaka', 'Esiop +päiväh, yli 7t/pv'), ('esiopetus_4h_61_100h_vuoroh', 'Esiopetus + Vuorohoito 61-100h/kk'), ('esiopetus_4h_101_160h_vuoroh', 'Esiopetus + Vuorohoito 101-160h/kk'), ('esiopetus_4h_160h_vuoroh', 'Esiopetus + Vuorohoito yli 160h/kk')], max_length=32, verbose_name='Laajuus yhteensä'),
        ),
        migrations.RunPython(migrate_hoidon_tarve, migrations.RunPython.noop),
    ]
